### ISSUE TITLE
Conditional Exports: Supporting both import and require() 

### ISSUE THREAD

**Issue by juergenzimmermann** [sindresorhus/strip-indent#12]
https://dev.to/bnb/conditional-exports-supporting-both-import-and-require-3ihg explains how to support both import and require().

**Comment by sindresorhus** [comment]
Sorry, I don't plan to support both.

**Comment by awwright** [comment]
I was about to file a bug because I couldn't figure out how to get strip-indent to work in Node.js. I don't think ending support for Node.js is reasonable. I'm just going to have to lock at an older version, or maybe hard-code an algorithm.
