### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by alexturpin** [sindresorhus/strip-indent#5]
Hi!

This module is great but unfortunately doesn't work in IE11 because of the arrow function. Would you accept a PR that changes it to an ES5 function?

Cheers

**Comment by SamVerschueren** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by alexturpin** [comment]
Interesting, thanks for the suggestion!
